"""Subtitle Management page — discover soft-subtitle .vtt files and run OCR
on hardsubbed videos that don't have a separate subtitle track.

Subtitle sources (priority order):
  1. Soft .vtt downloaded alongside the video by yt-dlp  (best quality)
  2. OCR-extracted .vtt generated by this page            (good for hardsubs)
  3. None — video not yet usable for subtitle-alignment training

EasyOCR is used with Slovak ('sk') as the target language.
First run downloads the model (~100 MB) automatically.
"""
import sys
import time
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))
from spj.inventory import pose_exists
from concurrent.futures import ThreadPoolExecutor, as_completed

from spj.ocr_subtitles import (
    ensure_reader,
    extract_debug_frame,
    extract_subtitles,
    get_subtitle_status,
    gpu_backend,
    ocr_vtt_path,
    read_vtt,
)

DATA_DIR      = Path(__file__).parent.parent.parent / "data"
INVENTORY_CSV = DATA_DIR / "inventory.csv"
POSE_DIR      = DATA_DIR / "pose"
SUBTITLES_DIR = DATA_DIR / "subtitles"

SUBTITLES_DIR.mkdir(parents=True, exist_ok=True)

st.header("6. 📝 Subtitles")

# GPU status banner
_backend = gpu_backend()
if _backend == "Apple Vision":
    _backend_color = "🟢"
    _backend_note  = " — macOS Neural Engine (fastest, no model download)"
elif _backend in ("MPS", "CUDA"):
    _backend_color = "🟢"
    _backend_note  = f" — GPU-accelerated EasyOCR on {_backend}"
else:
    _backend_color = "🟡"
    _backend_note  = " — EasyOCR on CPU (install ocrmac for Apple Vision speed)"
st.caption(
    f"{_backend_color} OCR backend: **{_backend}**{_backend_note}"
    + "   |   Soft subtitles downloaded by yt-dlp are used automatically. "
    "For hardsubbed videos OCR extracts the Slovak text from the frame."
)
st.caption("Page 6/10 · Find or extract the Slovak subtitle text for each video.")
with st.expander("ℹ️ How to use this page", expanded=False):
    st.markdown("""
**Needs:**
- Inventory scanned (page 1 — Inventory)

**Steps:**
1. Click **Discover soft subtitles** — finds `.vtt` files that yt-dlp downloaded automatically.
   These are the best quality — use them when available.
2. For videos marked *No subtitle*: select them and click **Run OCR extraction**.
   OCR reads the burned-in Slovak text from the bottom of the frame.
3. Use **Debug frame** to verify OCR is reading the correct subtitle region before running on all.

**Creates:** `data/subtitles/<videoname>.vtt` (one per video)
""")

with st.expander("ℹ️ Terminal warnings explained", expanded=False):
    st.markdown(
        """
**`objc: Class AVFFrameReceiver implemented in both cv2 … and av …`**
Two packages (`opencv-python` and `PyAV`) bundle different versions of the same
macOS library. This is harmless — the warning comes from macOS's dynamic linker,
not from your code. Results are not affected.

**`Downloading recognition model, please wait…`** *(EasyOCR only)*
EasyOCR downloads the Slovak recognition model (~100 MB) on the very first run.
Subsequent runs use the cached model and start in seconds.
When **Apple Vision** is the backend (macOS + ocrmac installed) no download occurs —
Apple Vision uses the on-device model built into macOS.

**`pin_memory not supported on MPS`** *(EasyOCR only)*
PyTorch warning — Apple Silicon MPS GPU doesn't support `pin_memory`.
EasyOCR falls back to normal memory automatically.  No action needed.
Not shown when Apple Vision is active.
        """
    )

# ------------------------------------------------------------------ #
# Load inventory
# ------------------------------------------------------------------ #
inv: pd.DataFrame | None = st.session_state.get("inventory")
if inv is None:
    if INVENTORY_CSV.exists():
        inv = pd.read_csv(INVENTORY_CSV)
        st.session_state["inventory"] = inv
    else:
        st.warning("No inventory found. Go to the **Inventory** page first.")
        st.stop()

if inv.empty:
    st.warning("Inventory is empty.")
    st.stop()

# ------------------------------------------------------------------ #
# Build status table
# ------------------------------------------------------------------ #
rows = []
for _, row in inv.iterrows():
    vpath  = Path(row["path"])
    status = get_subtitle_status(vpath, SUBTITLES_DIR)
    # Check for bilingual secondary VTT (.en.vtt)
    en_vtt = SUBTITLES_DIR / f"{vpath.stem}.en.vtt"
    has_en = en_vtt.exists() and en_vtt.stat().st_size > 8
    rows.append({
        "filename":    vpath.name,
        "subtitle":    status["source"],          # 'soft' | 'ocr' | 'none'
        "vtt_file":    status["vtt_path"].name if status["vtt_path"] else "—",
        "en":          "yes" if has_en else "",
        "_path":       str(vpath),
        "_vtt":        str(status["vtt_path"]) if status["vtt_path"] else "",
        "_source":     status["source"],
    })

status_df = pd.DataFrame(rows)

soft_count = (status_df["_source"] == "soft").sum()
ocr_count  = (status_df["_source"] == "ocr").sum()
none_count = (status_df["_source"] == "none").sum()

col1, col2, col3, col4 = st.columns(4)
col1.metric("Total videos",   len(status_df))
col2.metric("Soft subtitles", int(soft_count))
col3.metric("OCR extracted",  int(ocr_count))
col4.metric("No subtitles",   int(none_count))

# Colour-coded status table with selection
display_df = status_df[["filename", "subtitle", "vtt_file", "en"]].copy()
display_df.insert(0, "_sel", False)
edited_status = st.data_editor(
    display_df,
    column_config={"_sel": st.column_config.CheckboxColumn("✓", default=False, width="small")},
    hide_index=True,
    use_container_width=True,
    key="subtitle_table",
)

sel_idx = edited_status.index[edited_status["_sel"]].tolist()
if sel_idx:
    sel_rows  = status_df.iloc[sel_idx]
    has_vtt   = sel_rows[sel_rows["_vtt"] != ""]
    st.caption(f"{len(sel_idx)} selected  —  {len(has_vtt)} have a VTT file to delete")
    dc1, dc2 = st.columns([2, 3])
    with dc1:
        if st.button(
            f"🗑 Delete {len(has_vtt)} VTT file(s)",
            type="primary",
            disabled=has_vtt.empty,
        ):
            deleted = 0
            for _, r in has_vtt.iterrows():
                p = Path(r["_vtt"])
                if p.exists():
                    p.unlink()
                    deleted += 1
            st.success(f"Deleted {deleted} VTT file(s).")
            st.rerun()
    with dc2:
        st.caption("Deletes the .vtt subtitle file only — video files are not touched.")

# ------------------------------------------------------------------ #
# Preview a subtitle file
# ------------------------------------------------------------------ #
has_any = status_df[status_df["_source"] != "none"]
if not has_any.empty:
    with st.expander("Preview subtitles for a video", expanded=False):
        selected = st.selectbox(
            "Video",
            has_any["filename"].tolist(),
            key="subtitle_preview_select",
        )
        sel_row  = has_any[has_any["filename"] == selected].iloc[0]
        vtt_path = Path(sel_row["_vtt"])
        if vtt_path.exists():
            subs = read_vtt(vtt_path)
            if subs:
                prev_df = pd.DataFrame(subs)
                prev_df["start"] = prev_df["start_ms"].apply(
                    lambda ms: f"{ms//60000}:{(ms%60000)//1000:02d}.{ms%1000:03d}"
                )
                prev_df["end"] = prev_df["end_ms"].apply(
                    lambda ms: f"{ms//60000}:{(ms%60000)//1000:02d}.{ms%1000:03d}"
                )
                st.dataframe(
                    prev_df[["start", "end", "text"]],
                    use_container_width=True,
                    hide_index=True,
                )
                st.caption(f"{len(subs)} subtitle entries  —  {vtt_path.name}")
            else:
                st.info("VTT file is empty.")

# ------------------------------------------------------------------ #
# Debug frame inspector
# ------------------------------------------------------------------ #
with st.expander("🔬 Debug: inspect what OCR sees for a video", expanded=False):
    st.markdown(
        "Pick any video and a time offset to see exactly which region the OCR scans, "
        "how it looks after preprocessing, and what text is read. "
        "Use this to tune **region height** and **position** when OCR returns empty."
    )
    dbg_video = st.selectbox(
        "Video",
        inv["filename"].tolist(),
        key="dbg_video_select",
    )
    dbg_row  = inv[inv["filename"] == dbg_video].iloc[0]
    dbg_path = Path(dbg_row["path"])

    dbg_col1, dbg_col2, dbg_col3 = st.columns(3)
    with dbg_col1:
        dbg_time = st.number_input(
            "Time offset (seconds)",
            min_value=0, max_value=7200, value=10, step=5,
            key="dbg_time",
        )
    with dbg_col2:
        dbg_anchor = st.radio(
            "Subtitle position",
            ["bottom", "top"],
            index=0,
            horizontal=True,
            key="dbg_anchor",
        )
    with dbg_col3:
        dbg_frac = st.slider(
            "Region height",
            min_value=0.05, max_value=0.60, value=0.22, step=0.01,
            key="dbg_frac",
        )

    if st.button("🔍 Inspect frame", key="dbg_btn"):
        with st.spinner("Reading frame and running OCR…"):
            dbg = extract_debug_frame(
                dbg_path,
                time_sec=float(dbg_time),
                region_fraction=dbg_frac,
                region_anchor=dbg_anchor,
                language="sk",
            )

        if dbg.get("error"):
            st.error(dbg["error"])
        else:
            w, h = dbg["frame_size"]
            y0, y1 = dbg["region_y"]
            st.caption(
                f"Frame size: {w}×{h}  |  Scanned rows: {y0}–{y1} "
                f"({dbg_anchor}, {dbg_frac:.0%} of frame)"
            )

            img_col1, img_col2 = st.columns(2)
            with img_col1:
                st.markdown("**Full frame** — green box = scanned region")
                st.image(dbg["annotated_rgb"], use_container_width=True)
            with img_col2:
                st.markdown("**Subtitle strip** — colour (top) and binarised (bottom)")
                st.image(dbg["roi_rgb"], use_container_width=True)
                st.image(dbg["preprocessed"], use_container_width=True)

            ocr_result = dbg["ocr_text"]
            if ocr_result:
                st.success(f"OCR result: **{ocr_result}**")
            else:
                st.warning(
                    "OCR returned empty. Try: switch position bottom↔top, "
                    "increase region height, or check if subtitles appear at this timestamp."
                )

st.divider()

# ------------------------------------------------------------------ #
# OCR extraction for videos without subtitles
# ------------------------------------------------------------------ #
needs_ocr = status_df[status_df["_source"] == "none"].copy()

st.subheader("OCR extraction")

if needs_ocr.empty:
    st.success("All videos have subtitles — nothing to extract.")
else:
    st.markdown(
        f"**{len(needs_ocr)}** video(s) have no subtitle file. "
        "Run OCR to extract Slovak text from the burned-in subtitles."
    )
    st.dataframe(
        needs_ocr[["filename"]],
        use_container_width=True,
        hide_index=True,
    )

# Settings
with st.expander("OCR settings", expanded=False):
    st.markdown(
        "These control how the subtitle region is found and read. "
        "Defaults work well for most Slovak sign-language videos with "
        "white text on a dark background."
    )
    st.info(
        "**Speed:** pixel diff is checked every N frames (cheap). "
        "OCR only runs when the subtitle region visually changes — "
        "typically 200–600 times per hour of video instead of 18,000+."
    )
    c1, c2 = st.columns(2)
    with c1:
        ocr_language = st.selectbox(
            "Language",
            ["sk", "cs", "en"],
            index=0,
            help="sk = Slovak (default).  cs = Czech (same alphabet, similar accuracy).  "
                 "Model (~100 MB) is downloaded automatically on first use.",
        )
        region_anchor = st.radio(
            "Subtitle position",
            ["bottom", "top"],
            index=0,
            horizontal=True,
            help="Where burned-in subtitles appear. Most videos: bottom. "
                 "Some older or news-style videos place subtitles at the top.",
        )
        region_fraction = st.slider(
            "Subtitle region height (fraction of frame)",
            min_value=0.08, max_value=0.50, value=0.22, step=0.01,
            help=f"{'Bottom' if region_anchor == 'bottom' else 'Top'} N % of the frame "
                 "scanned for subtitle text. 22 % works for most SPJ videos.",
        )
        diff_sample_n = st.slider(
            "Diff check every N frames",
            min_value=1, max_value=10, value=3, step=1,
            help="Pixel diff is computed every N frames. 3 ≈ one check per 0.12 s at 25 fps. "
                 "Increase to speed up scanning; decrease for very fast subtitle changes.",
        )
    with c2:
        diff_threshold = st.slider(
            "Pixel diff threshold (0–50)",
            min_value=1.0, max_value=50.0, value=6.0, step=0.5,
            help="Mean absolute pixel change in subtitle region that triggers OCR. "
                 "Lower = more sensitive (catches subtle changes); "
                 "higher = ignores noise between frames.",
        )
        min_duration_ms = st.slider(
            "Min subtitle duration (ms)",
            min_value=100, max_value=2000, value=400, step=50,
            help="Subtitle entries shorter than this are discarded as noise.",
        )
        change_threshold = st.slider(
            "OCR text-change sensitivity (0–1)",
            min_value=0.50, max_value=0.99, value=0.80, step=0.01,
            help="Character-overlap ratio below which the new OCR result is treated "
                 "as different text. Handles minor frame-to-frame OCR noise.",
        )
        overwrite_ocr = st.checkbox(
            "Overwrite existing OCR files",
            value=False,
        )

ocr_params = dict(
    region_fraction  = region_fraction,
    region_anchor    = region_anchor,
    diff_sample_n    = diff_sample_n,
    diff_threshold   = diff_threshold,
    min_duration_ms  = min_duration_ms,
    change_threshold = change_threshold,
    language         = ocr_language,
)

# Target: videos with no subtitles, or all if overwrite
if overwrite_ocr:
    target_df = status_df.copy()
    btn_label = f"▶ Re-extract all {len(target_df)} video(s)"
else:
    target_df = needs_ocr
    btn_label = (
        f"▶ Extract subtitles from {len(needs_ocr)} video(s)"
        if not needs_ocr.empty
        else "No videos need OCR"
    )

if needs_ocr.empty and not overwrite_ocr:
    st.stop()

# Parallel workers slider — shown before the run button
n_workers = st.slider(
    "Parallel workers",
    min_value=1, max_value=6, value=2,
    help="Each worker reads a different video and runs OCR in parallel. "
         "All workers share the same loaded EasyOCR model (no extra RAM per worker). "
         "M4 Max with 40 GPU cores and 64 GB RAM can comfortably run 3–4 workers.",
)

if not st.button(btn_label, type="primary", disabled=target_df.empty):
    st.stop()

# ------------------------------------------------------------------ #
# Run OCR
# ------------------------------------------------------------------ #
total = len(target_df)

# Pre-warm the reader once in the main thread before spawning workers
# (avoids concurrent model downloads / multiple load races).
# For Apple Vision this is a no-op (stateless, no model to load).
_spinner_msg = (
    "Apple Vision ready — no model loading needed."
    if _backend == "Apple Vision"
    else f"Loading EasyOCR model [{ocr_language}] on {_backend}… (first run downloads ~100 MB)"
)
with st.spinner(_spinner_msg):
    try:
        ensure_reader(ocr_language)
    except ImportError as exc:
        st.error(
            f"No OCR backend available — run `uv sync` to install ocrmac / easyocr. "
            f"Detail: {exc}"
        )
        st.stop()

overall_bar = st.progress(0.0, text=f"0 / {total} completed")
st.markdown("**Active workers:**")
worker_placeholders: dict[str, object] = {}
log_out  = st.empty()

log_lines: list[str] = []
errors:    list[str] = []
completed = 0

# Shared progress dict written by worker threads, read by main thread
video_progress: dict[str, float] = {}

def _run_one(row: dict) -> tuple[str, int | Exception]:
    vpath   = Path(row["_path"])
    out_vtt = ocr_vtt_path(vpath, SUBTITLES_DIR)

    def _cb(frac: float):
        video_progress[str(vpath)] = frac

    try:
        subs = extract_subtitles(vpath, out_vtt, progress_callback=_cb, **ocr_params)
        return str(vpath), len(subs)
    except Exception as exc:
        return str(vpath), exc


target_rows = [row for _, row in target_df.iterrows()]

with ThreadPoolExecutor(max_workers=n_workers) as pool:
    futures = {pool.submit(_run_one, row): Path(row["_path"]) for row in target_rows}

    # Initialise per-worker progress bars for first batch
    for vpath in list(futures.values())[:n_workers]:
        worker_placeholders[str(vpath)] = st.empty()
        worker_placeholders[str(vpath)].progress(0.0, text=f"⏳ {vpath.name}")

    pending = set(futures.keys())
    while pending:
        # Refresh per-video progress bars
        for vpath_str, ph in list(worker_placeholders.items()):
            frac = video_progress.get(vpath_str, 0.0)
            ph.progress(min(frac, 1.0), text=f"⏳ {Path(vpath_str).name}  {frac*100:.0f}%")

        done_now = {f for f in pending if f.done()}
        pending  -= done_now

        for future in done_now:
            vpath      = futures[future]
            vpath_str  = str(vpath)
            placeholder = worker_placeholders.pop(vpath_str, None)
            if placeholder:
                placeholder.empty()

            vpath_str_result, result = future.result()
            if isinstance(result, Exception):
                line = f"❌ `{vpath.name}` — {result}"
                errors.append(line)
            else:
                line = f"✅ `{vpath.name}` — {result} subtitle entries"

            log_lines.append(line)
            completed += 1
            overall_bar.progress(completed / total, text=f"{completed} / {total} completed")
            log_out.markdown("\n\n".join(log_lines[-20:]))

            # Assign freed slot to next pending video
            next_videos = [futures[f] for f in pending if str(futures[f]) not in worker_placeholders]
            if next_videos:
                nxt = next_videos[0]
                worker_placeholders[str(nxt)] = st.empty()
                worker_placeholders[str(nxt)].progress(0.0, text=f"⏳ {nxt.name}")

        import time as _time
        _time.sleep(0.2)

overall_bar.progress(1.0, text=f"{total} / {total} done")

if errors:
    with st.expander(f"Errors ({len(errors)})"):
        for e in errors:
            st.markdown(e)

ok = total - len(errors)
st.success(f"OCR complete — {ok} / {total} videos processed. VTT files saved to `data/subtitles/`.")
st.rerun()
